### ISSUE TITLE
gelöst:HMIP-PS Schaltsteckdose lässt sich über XML-API nicht ansteuern

### ISSUE THREAD

**Issue by lupos-w** [jens-maus/XML-API#44]
Ich komme hier nicht weiter. Habe seid Jahren die XML-API im Einsatz mit Homematic IP Dimmaktor Unterputz HMIP-FDT und 4 Kanal Schaltaktor HM-LC-Sw4-WM. Problemos ...nun habe ich mir zwei Schaltsteckdosen HMIP-PS zugelegt und wollte diese ebenfalls über die XML-API steuern. Die Kommunikation läuft fehlerfrei. Aber die Steckdosen schalten nicht. 
Aufruf ist identisch wie bei den andern Aktuatoren.  http://192.168.xxx.xxx/config/xmlapi/statechange.cgi?ise_id=1234&new_value=1
id ist vom ch3 bzw. Schaltaktor Kanal der Schaltsteckdose.  Aus der Homematic Web Oberfläche schalten die Steckdosen...kann es sein das die HMip-PS per XML nicht funktioniert ?

**Comment by HolgerJeromin** [comment]
Tut hier. Die Frage ist, ob du die richtige iseid benutzt. 
Das fand ich am Anfang schwer programatisch rauszukriegen. 
Ich muss dafür devicelist und statelist analysieren.

**Comment by lupos-w** [comment]
ja hab ich mehrmals geprüft und auch zur Sicherheit alle "falschen" durchprobiert....das wäre ja zu reinfach...

**Comment by HolgerJeromin** [comment]
> Damit benimmt die sich definitv anders als die anderen Aktuatoren....

Gibt noch andere Aktoren (mindestens HmIP-BSM) wo ich drüber gestolpert bin.

> egal funktioniert jetzt...Danke.

Gerne.
